---
- hosts: All_nodes
  become: yes
  vars_files:
    - vars.yml
  roles:
    - openssh
    - jdk
    - spark
    - zeppelin

- hosts: Master_node
  become: no
  vars_files:
    - vars.yml
  roles:
    - launch

- hosts: Zeppelin_node
  become: no
  vars_files:
    - vars.yml
  roles:
    - start_zeppelin
