---
- hosts: cham_cloud #comment: apache is the group name we just defined
  become: yes #comment: this operation needs privilege access
  become_user: hadoop
  tasks:
    - name: get output to cloud
      shell: "sh -lc 'hdfs dfs -get /harshit/harshit_output /home/hadoop/harshit_output'"


