---

-   hosts: dbserver
    remote_user: "{{ uname }}"
    become: yes
    become_method: sudo

    roles:
        - mongo

-   hosts: appserver
    remote_user: "{{ uname }}"
    become: yes
    become_method: sudo
    roles:
        - pip
        - projectearth
