#!/usr/bin/env python
# -*- elpy-mode: nil; auto-complete-mode: nil; company-mode: nil -*-

from subprocess import check_call, CalledProcessError
import glob
import sys

hid_dirs = sys.argv[1:]

for path in hid_dirs:
    cmd = ['make', '-C', path]
    print 'Building %s' % path
    print ' '.join(cmd)

    try:
        check_call(cmd)
        print 'OK'
    except CalledProcessError, e:
        print 'FAIL'
        raise
