all:
	pdflatex vonLaszewski-i524-chameleon
	bibtex vonLaszewski-i524-chameleon
	pdflatex vonLaszewski-i524-chameleon
	pdflatex vonLaszewski-i524-chameleon


view:
	open vonLaszewski-i524-chameleon.pdf
