mongo:
	pdflatex vonLaszewski-i524-mongodb
	bibtex vonLaszewski-i524-mongodb
	pdflatex vonLaszewski-i524-mongodb
	pdflatex vonLaszewski-i524-mongodb
	open vonLaszewski-i524-mongodb.pdf

class:
	pdflatex vonLaszewski-i524-chameleon
	bibtex vonLaszewski-i524-chameleon
	pdflatex vonLaszewski-i524-chameleon
	pdflatex vonLaszewski-i524-chameleon
	open vonLaszewski-i524-chameleon.pdf

view:

