---
#This Playbook configures the mongos service of mongodb

- name: Create the mongos startup file
  template: src=mongos.j2 dest=/etc/init.d/mongos mode=0655


- name: Create the mongos configuration file
  template: src=mongos.conf.j2 dest=/etc/mongos.conf

- name: Copy the keyfile for authentication
  copy: src=roles/mongod/files/secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400

- name: Start the mongos service
  command: creates=/var/lock/subsys/mongos /etc/init.d/mongos start
  with_items: groups.all
  become: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"


- name: Start the mongodb service
    systemd:
      name: mongos
      state: restarted
      daemon_reload: yes
    become: true
    with_items: groups.all
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"

- name: pause
  pause: seconds=20

- name: copy the file for shard test
  template: src=testsharding.j2 dest=/tmp/testsharding.js

- name: copy the file enable  sharding
  template: src=enablesharding.j2 dest=/tmp/enablesharding.js
