#!/usr/bin/env bash
# 1) accept the veracity of the other nodes in the cluster; 
# 2) ansible seems to hang if this is not done first
# 3) run the ansible script
# 4) setup and start the robots

echo "Adding static ip addresses to master node host file"
cut -d' ' -f1 ~/addMeToHostFiles.list > ~/inventoryInter.txt

node_ip01=$(sed -n '1p' ~/inventoryInter.txt)
echo $node_ip01
ssh -o StrictHostKeyChecking=no cc@$node_ip01 hostname

node_ip02=$(sed -n '2p' ~/inventoryInter.txt)
echo $node_ip02
ssh -o StrictHostKeyChecking=no cc@$node_ip02 hostname

node_ip03=$(sed -n '3p' ~/inventoryInter.txt)
echo $node_ip03
ssh -o StrictHostKeyChecking=no cc@$node_ip03 hostname

rm ~/inventoryInter.txt

#start the Ansible script
cd ~/ansibleScript
ansible-playbook -i inventory.txt rosSetup.yml

#prepare the mybot_ws workspace
cd /opt/ros/kinetic
source setup.bash
cd /home/cc/mybot_ws
catkin clean --yes
catkin build
source devel/setup.bash
echo "source /home/cc/mybot_ws/devel/setup.bash" >> /home/cc/.bashrc

# start talker.py on node #2
## start roscore
ssh cc@$node_ip02 wget -P /home/cc/ https://raw.githubusercontent.com/cloudmesh/cloudmesh.ros/master/code/talkListen
ssh -o StrictHostKeyChecking=no cc@$node_ip02 chmod +x /home/cc/talkListen
ssh -o StrictHostKeyChecking=no cc@$node_ip02 ./talkListen

# start the simulation and command the robots to move
sleep 90 && rostopic pub /robot1/cmd_vel geometry_msgs/Twist '{linear: {x: 0.2, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.1}}'&
sleep 90 && rostopic pub /robot2/cmd_vel geometry_msgs/Twist '{linear: {x: 0.2, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.1}}'&
(
	roslaunch mybot_gazebo mybot_world.launch
)

timeEnd=$SECONDS
totTime=$timeEnd-$timeBgn
echo "Total Run Time:  $(($totTime % 60))sec" > /home/cc/timer.txt

echo "beginAgain completed"