#!/usr/bin/env bash
cut -d' ' -f1 ~/addMeToHostFiles.list > ~/inventoryInter.txt

node_ip01=$(sed -n '1p' ~/inventoryInter.txt)
#echo $node_ip01
ssh -o StrictHostKeyChecking=no cc@$node_ip01 hostname

node_ip02=$(sed -n '2p' ~/inventoryInter.txt)
#echo $node_ip02
ssh -o StrictHostKeyChecking=no cc@$node_ip02 hostname

node_ip03=$(sed -n '3p' ~/inventoryInter.txt)
#echo $node_ip03
ssh -o StrictHostKeyChecking=no cc@$node_ip03 hostname

SESSION=$USER
byobu-tmux -2 new-session -d -s $SESSION
byobu-tmux split-window -v
byobu-tmux select-pane -t 1
byobu-tmux split-window -h
byobu-tmux select-pane -t 1
byobu-tmux -2 send-keys "roscore" C-m
byobu-tmux select-pane -t 2
byobu-tmux -2 send-keys "rosrun rospy_tutorials talker.py" C-m
byobu-tmux select-pane -t 0
byobu-tmux -2 send-keys "ssh -o StrictHostKeyChecking=no  cc@$node_ip03" C-m
byobu-tmux -2 attach-session -t $SESSION